language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: 
  - "pip install -r requirements.txt --use-mirrors"
#  - "pip install nose coveralls"
script: 
    python manage.py test
#  nosetests --with-coverage --cover-package=acmx_website
#after_success:
#  coveralls
